### PR TITLE
fix: 适配amd64\arm64\loongarch64架构

### PR DESCRIPTION
**Pull request by anderly011**
Description: 适配amd64\arm64\loongarch64架构

### CODE REVIEW

**Comment by felixonmars** [comment]
Where/How were these binaries obtained/produced? Say, what if we need to update or support more architectures in the future?

**Comment by RevySR** [comment]
https://github.com/deepin-community/rfcs/issues/9
二进制仓库接收讨论

**Comment by RevySR** [comment]
根据使用说明
loongarch架构二进制似乎是ABI 1.0 不满足入仓要求

**Comment by anderly011** [comment]
> Where/How were these binaries obtained/produced? Say, what if we need to update or support more architectures in the future?

**Comment by anderly011** [comment]
> Where/How were these binaries obtained/produced? Say, what if we need to update or support more architectures in the future?

i have updated a README file.

**Comment by Zeno-sole** [comment]
原则上不接收二进制，关闭此PR

**Pull request closed without merging**
